# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-18 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='karbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
            ],
        ),
    ]
