# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-08-18 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='email',
            field=models.EmailField(max_length=80, unique=True),
        ),
    ]
